"""Parse Bricklink XML inventory files."""

from typing import Dict, List
from lxml import etree


class Part:
    """Represents a LEGO part from inventory."""
    
    def __init__(self, item_id: str, item_type: str, color_id: str, 
                 qty: int, category_id: str = None, name: str = None):
        self.item_id = item_id
        self.item_type = item_type
        self.color_id = color_id
        self.qty = qty
        self.category_id = category_id
        self.name = name
    
    def __repr__(self):
        return f"Part({self.item_id}, type={self.item_type}, color={self.color_id}, qty={self.qty})"


class BricklinkXMLParser:
    """Parser for Bricklink XML files generated by BrickStore."""
    
    def parse_file(self, filepath: str) -> List[Part]:
        """Parse a Bricklink XML file and return list of parts."""
        try:
            tree = etree.parse(filepath)
            root = tree.getroot()
            
            parts = []
            for item in root.findall('.//ITEM'):
                item_type = self._get_text(item, 'ITEMTYPE')
                item_id = self._get_text(item, 'ITEMID')
                color_id = self._get_text(item, 'COLOR')
                qty = int(self._get_text(item, 'MINQTY', '0'))
                category_id = self._get_text(item, 'CATEGORY')
                name = self._get_text(item, 'ITEMNAME')
                
                parts.append(Part(
                    item_id=item_id,
                    item_type=item_type,
                    color_id=color_id,
                    qty=qty,
                    category_id=category_id,
                    name=name
                ))
            
            return parts
        except Exception as e:
            raise ValueError(f"Failed to parse XML file: {e}")
    
    def _get_text(self, element, tag: str, default: str = '') -> str:
        """Safely extract text from XML element."""
        child = element.find(tag)
        return child.text if child is not None and child.text else default
